export const LIKE_DESIGN         = 'LIKE_DESIGN';
export const DISLIKE_DESIGN      = 'DISLIKE_DESIGN';
export const REQUEST_DESIGNS     = 'REQUEST_DESIGNS';
export const RECEIVE_DESIGNS     = 'RECEIVE_DESIGNS';
export const LOAD_CACHED_DESIGNS = 'LOAD_CACHED_DESIGNS';